
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDBUNDLEPRODUCTS" (
   
	   p_BUNDLE_TYPE_CD IN bundle_products.BUNDLE_TYPE_CD%TYPE,
     p_PRODUCT_ID  IN bundle_products.PRODUCT_ID %TYPE,
     p_END_DATE IN bundle_products.END_DATE%TYPE,
     p_BIZ_CON_IND IN bundle_products.BIZ_CON_IND%TYPE,
     p_PRODUCT_TYPE IN bundle_products.PRODUCT_TYPE%TYPE,
     p_WORK_REQST_ID IN bundle_products.WORK_REQST_NO%TYPE)
AS
BEGIN
  INSERT INTO BUNDLE_PRODUCTS("BUNDLE_TYPE_CD","PRODUCT_ID","START_DATE","END_DATE","BIZ_CON_IND","WORK_REQST_NO","LAST_UPDATED","PRODUCT_TYPE") 
  VALUES(p_BUNDLE_TYPE_CD,p_PRODUCT_ID,SYSDATE,p_END_DATE,p_BIZ_CON_IND,p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval),SYSDATE,p_PRODUCT_TYPE);
  COMMIT;
END;
/
 