
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDBUNDLETYPE" (
     p_BUNDLE_LEVEL_CD IN BUNDLE_TYPES.BUNDLE_LEVEL_CD%TYPE,
     p_BUNDLE_DESC IN BUNDLE_TYPES.BUNDLE_DESC%TYPE,
     p_WORK_REQST_ID IN BUNDLE_TYPES.WORK_REQST_NO%TYPE)
AS
BEGIN

  INSERT INTO BUNDLE_TYPES("BUNDLE_TYPE_CD","BUNDLE_LEVEL_CD","BUNDLE_DESC","WORK_REQST_NO","LAST_UPDATED") 
  VALUES('B'||to_char(bundle_key.nextval),p_BUNDLE_LEVEL_CD,p_BUNDLE_DESC,p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval),SYSDATE);
  COMMIT;
END;
/
 