
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDPACKAGEFILTERS" (
   
    P_PACKAGE_ID IN package_filters.PACKAGE_ID%TYPE,
    P_PRODUCT_ID IN package_filters.PRODUCT_ID%TYPE,
    P_FILTER_TYPE IN package_filters.FILTER_TYPE%TYPE,
    P_END_DATE IN package_filters.END_DATE%TYPE,
    P_FILTER_VALUE1 IN package_filters.FILTER_VALUE1%TYPE,
    P_IS_ACTIVE IN package_filters.IS_ACTIVE %TYPE,
    p_WORK_REQST_ID IN package_filters.WORK_REQST_NO%TYPE)
AS
BEGIN

  INSERT INTO package_filters ("PACKAGE_ID","PRODUCT_ID","START_DATE","FILTER_TYPE","END_DATE","FILTER_VALUE1","LAST_UPDATED","IS_ACTIVE","WORK_REQST_NO") 
  VALUES (P_PACKAGE_ID,P_PRODUCT_ID,sysdate,P_FILTER_TYPE,P_END_DATE,P_FILTER_VALUE1,SYSDATE,P_IS_ACTIVE,p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval));
  COMMIT;
END;
/
 