
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDPACKAGEPRODUCT" (
    P_PACKAGE_ID IN PACKAGE_PRODUCTS.PACKAGE_ID% TYPE,
    P_PRODUCT_ID IN PACKAGE_PRODUCTS.PRODUCT_ID%TYPE,
	   p_ORDER_TYPE IN PACKAGE_PRODUCTS.ORDER_TYPE%TYPE,
	    --p_START_DATE IN PACKAGE_PRODUCTS.START_DATE%TYPE,
	   p_END_DATE IN PACKAGE_PRODUCTS.END_DATE%TYPE,
     p_ITEM_MIN IN PACKAGE_PRODUCTS.ITEM_MIN%TYPE,
     p_ITEM_MAX  IN PACKAGE_PRODUCTS.ITEM_MAX %TYPE,
     p_PKG_PROD_GRANDFATHERED IN PACKAGE_PRODUCTS.PKG_PROD_GRANDFATHERED%TYPE,
    -- p_LAST_UPDATED IN PRODUCTS.LAST_UPDATED%TYPE, 
    
     p_WORK_REQST_ID IN PRODUCTS.WORK_REQST_NO%TYPE)
AS
BEGIN

  INSERT INTO  PACKAGE_PRODUCTS ("PACKAGE_ID","PRODUCT_ID","ORDER_TYPE", "START_DATE", "END_DATE","ITEM_MIN","ITEM_MAX","LAST_UPDATED","PKG_PROD_GRANDFATHERED","WORK_REQST_NO") 
  VALUES (P_PACKAGE_ID,P_PRODUCT_ID, p_ORDER_TYPE, sysdate, p_END_DATE,p_ITEM_MIN,p_ITEM_MAX,SYSDATE,p_PKG_PROD_GRANDFATHERED, p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval));
  COMMIT;
END;


/
 