
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDPRODUCT" (
    --P_PRODUCT_ID IN PRODUCTS.PRODUCT_ID%TYPE,
	   p_PRODUCT_NAME IN PRODUCTS.PRODUCT_NAME%TYPE,
	 --  p_BILLING_SYSTEM  IN PRODUCTS.BILLING_SYSTEM%TYPE,
	  -- p_BILLING_CODE IN PRODUCTS.BILLING_CODE%TYPE,
     p_PRODUCT_TYPE IN PRODUCTS.PRODUCT_TYPE%TYPE,
     p_PRODUCT_TYPE_VALUE IN PRODUCTS.PRODUCT_TYPE_VALUE%TYPE,
     p_GRANDFATHERED IN PRODUCTS.GRANDFATHERED%TYPE,
    -- p_LAST_UPDATED IN PRODUCTS.LAST_UPDATED%TYPE, 
     --p_PROD_STARTDATE IN PRODUCTS.PROD_STARTDATE%TYPE, 
     p_PROD_ENDDATE IN PRODUCTS.PROD_ENDDATE%TYPE, 
     p_PRODUCT_DESC IN PRODUCTS.PRODUCT_DESC%TYPE,
     p_WORK_REQST_ID IN PRODUCTS.WORK_REQST_NO%TYPE)
AS
BEGIN

  INSERT INTO PRODUCTS ("PRODUCT_ID","PRODUCT_NAME", "BILLING_SYSTEM", "BILLING_CODE","PRODUCT_TYPE","PRODUCT_TYPE_VALUE","GRANDFATHERED","LAST_UPDATED","PROD_STARTDATE","PROD_ENDDATE","PRODUCT_DESC","WORK_REQST_NO") 
  VALUES ('P'||to_char(pro_id.nextval), p_PRODUCT_NAME,'BES','007',p_PRODUCT_TYPE, p_PRODUCT_TYPE_VALUE, p_GRANDFATHERED,SYSDATE,SYSDATE,p_PROD_ENDDATE,p_PRODUCT_DESC, p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval));
  COMMIT;
END;
/
 