
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDPACKAGE" (
   
	   p_PACKAGE_NAME IN PACKAGE.PACKAGE_NAME%TYPE,
	 
	  -- p_BILLING_CODE IN PACKAGE.BILLING_CODE%TYPE,
     p_CATEGORY_ID IN PACKAGE.CATEGORY_ID %TYPE,
     
     p_GRANDFATHERED IN PACKAGE.GRANDFATHERED%TYPE,
   
     p_PACKAGE_TYPE IN PACKAGE.PACKAGE_TYPE%TYPE, 
     
     p_PKG_DETAIL_DESCR  IN PACKAGE.PKG_DETAIL_DESCR%TYPE,
     
     p_PCR_DROP_DATE IN PACKAGE.PKG_DETAIL_DESCR%TYPE,
     
      p_WORK_REQST_ID IN PACKAGE.WORK_REQST_NO%TYPE)
AS
BEGIN

  INSERT INTO PACKAGE ("PACKAGE_ID","PACKAGE_NAME","BILLING_CODE","CATEGORY_ID","GRANDFATHERED","PACKAGE_TYPE","LAST_UPDATED","PKG_DETAIL_DESCR","PCR_DROP_DATE","WORK_REQST_NO") 
  VALUES ('Pa'||to_char(pack_id.nextval),p_PACKAGE_NAME,'007',p_CATEGORY_ID, p_GRANDFATHERED,p_PACKAGE_TYPE,SYSDATE, p_PKG_DETAIL_DESCR,p_PCR_DROP_DATE, p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval));
  COMMIT;
END;
/
 