
  CREATE OR REPLACE PROCEDURE "SYSTEM"."ADDRATES" (
   
    p_PRODUCT_ID IN RATES.PRODUCT_ID%TYPE,
    p_STATE IN RATES.STATE% TYPE,
	   p_BILLING_FREQ_ID IN RATES.BILLING_FREQ_ID%TYPE,
     p_BAND_PRODUCT_ID IN  RATES.BAND_PRODUCT_ID%TYPE,
	    --p_START_DATE IN PACKAGE_PRODUCTS.START_DATE%TYPE,
	   p_END_DATE IN RATES.END_DATE%TYPE,
     p_RATE_VALUE IN RATES.RATE_VALUE%TYPE,
    -- p_LAST_UPDATED IN PRODUCTS.LAST_UPDATED%TYPE, 
    
     p_WORK_REQST_ID IN RATES.WORK_REQST_NO%TYPE,
     p_STATE_ID IN RATES.STATE_ID%TYPE)
AS
BEGIN

  INSERT INTO  RATES ("PRODUCT_ID","STATE","BILLING_FREQ_ID","BAND_PRODUCT_ID","START_DATE","END_DATE","RATE_VALUE","LAST_UPDATED","WORK_REQST_NO","STATE_ID") 
  VALUES (P_PRODUCT_ID,p_STATE,p_BILLING_FREQ_ID,p_BAND_PRODUCT_ID, sysdate, p_END_DATE, p_RATE_VALUE,SYSDATE,p_WORK_REQST_ID||to_char(WORK_REQST_SEQ.nextval),p_STATE_ID);
  COMMIT;
END;
/
 