
  CREATE TABLE "SYSTEM"."BUNDLE_TYPES" 
   (	"BUNDLE_TYPE_CD" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"BUNDLE_LEVEL_CD" VARCHAR2(15 BYTE), 
	"BUNDLE_DESC" VARCHAR2(150 BYTE), 
	"WORK_REQST_NO" VARCHAR2(20 BYTE), 
	"LAST_UPDATED" DATE, 
	 CONSTRAINT "BUNDLE_TYPES_PK" PRIMARY KEY ("BUNDLE_TYPE_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
