
  CREATE TABLE "SYSTEM"."BUNDLE_PRODUCTS" 
   (	"BUNDLE_TYPE_CD" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PRODUCT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"BIZ_CON_IND" VARCHAR2(1 BYTE), 
	"WORK_REQST_NO" VARCHAR2(20 BYTE), 
	"LAST_UPDATED" DATE, 
	"PRODUCT_TYPE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "BUNDLE_PRODUCTS_PK" PRIMARY KEY ("BUNDLE_TYPE_CD", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "BUNDLE_PRODUCTS_BUNDLE_TY_FK1" FOREIGN KEY ("BUNDLE_TYPE_CD")
	  REFERENCES "SYSTEM"."BUNDLE_TYPES" ("BUNDLE_TYPE_CD") ENABLE, 
	 CONSTRAINT "BUNDLE_PRODUCTS_PRODUCTS_FK1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
