
  CREATE TABLE "SYSTEM"."PRODUCTS" 
   (	"PRODUCT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"BILLING_SYSTEM" VARCHAR2(10 BYTE), 
	"BILLING_CODE" VARCHAR2(25 BYTE), 
	"PRODUCT_TYPE" VARCHAR2(20 BYTE), 
	"PRODUCT_TYPE_VALUE" VARCHAR2(50 BYTE), 
	"GRANDFATHERED" VARCHAR2(1 BYTE), 
	"LAST_UPDATED" DATE, 
	"PROD_STARTDATE" DATE, 
	"PROD_ENDDATE" DATE, 
	"PRODUCT_DESC" VARCHAR2(200 BYTE), 
	"WORK_REQST_NO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "PRODUCTS_UK1" UNIQUE ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

  CREATE UNIQUE INDEX "SYSTEM"."PRODUCTS_PK" ON "SYSTEM"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
  CREATE UNIQUE INDEX "SYSTEM"."PRODUCTS_UK1" ON "SYSTEM"."PRODUCTS" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
