
  CREATE TABLE "SYSTEM"."RATES" 
   (	"PRODUCT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BILLING_FREQ_ID" NUMBER(22,0), 
	"BAND_PRODUCT_ID" VARCHAR2(20 BYTE), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"RATE_VALUE" NUMBER(22,0), 
	"LAST_UPDATED" DATE, 
	"WORK_REQST_NO" VARCHAR2(20 BYTE), 
	"STATE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RATES_PK" PRIMARY KEY ("PRODUCT_ID", "START_DATE", "STATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "RATES_PRODUCTS_FK1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
