CREATE TABLE BUNDLE_TYPES
(
  BUNDLE_TYPE_CD VARCHAR2(10) NOT NULL,
  BUNDLE_LEVEL_CD VARCHAR2(15),
  BUNDLE_DESC VARCHAR2(150),
  WORK_REQST_NO VARCHAR2(20),
  LAST_UPDATED DATE
, CONSTRAINT BUNDLE_TYPES_PK PRIMARY KEY
  (
    BUNDLE_TYPE_CD
  )
  ENABLE
)
;
