CREATE TABLE BUNDLE_PRODUCTS
(
  BUNDLE_TYPE_CD VARCHAR2(10) NOT NULL,
  PRODUCT_ID VARCHAR2(20) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  BIZ_CON_IND VARCHAR2(1),
  WORK_REQST_NO VARCHAR2(20),
  LAST_UPDATED DATE,
  PRODUCT_TYPE VARCHAR2(20)
, CONSTRAINT BUNDLE_PRODUCTS_PK PRIMARY KEY
  (
    BUNDLE_TYPE_CD,
    PRODUCT_ID
  )
  ENABLE
)
;

ALTER TABLE BUNDLE_PRODUCTS
ADD CONSTRAINT BUNDLE_PRODUCTS_BUNDLE_TY_FK1 FOREIGN KEY
(
  BUNDLE_TYPE_CD
)
REFERENCES BUNDLE_TYPES
(
BUNDLE_TYPE_CD
) ENABLE
;

ALTER TABLE BUNDLE_PRODUCTS
ADD CONSTRAINT BUNDLE_PRODUCTS_PRODUCTS_FK1 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES PRODUCTS
(
PRODUCT_ID
) ENABLE
;
