CREATE TABLE RATES
(
  PRODUCT_ID VARCHAR2(20) NOT NULL,
  STATE_CODE VARCHAR2(2) NOT NULL,
  BILLING_FREQ_ID NUMBER(22, 0),
  BAND_PRODUCT_ID VARCHAR2(20),
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  RATE_VALUE NUMBER(22, 0),
  LAST_UPDATED DATE,
  WORK_REQST_NO VARCHAR2(20)
, CONSTRAINT RATES_PK PRIMARY KEY
  (
    PRODUCT_ID,
    STATE_CODE,
    START_DATE
  )
  ENABLE
)
;

ALTER TABLE RATES
ADD CONSTRAINT RATES_PRODUCTS_FK1 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES PRODUCTS
(
PRODUCT_ID
) ENABLE
;
